development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: deh7r3fh181i83
  pool: 5
  username: nkoukzzxopvxco
  password: vyMxv2Fm0eI4L-jBGpv9_rzq-D
  host: ec2-54-83-55-214.compute-1.amazonaws.com